## Scaling in Machine Learning

Scaling refers to the process of standardizing or normalizing the features of a dataset so that they can contribute equally to the model's performance. This is crucial because many machine learning algorithms, such as gradient descent-based methods (e.g., linear regression, logistic regression) and distance-based algorithms (e.g., k-nearest neighbors, support vector machines), are sensitive to the scale of the input features.

## Types of Scaling

#### 1. Standardization (Z-score Normalization)
- Transforms data to have a mean of 0 and a standard deviation of 1
- Formula: `z = (x - μ)/σ`
- Useful when the data follows a Gaussian distribution

#### 2. Min-Max Scaling
- Scales the data to a fixed range, usually [0, 1]
- Formula: `x' = (x - min(x))/(max(x) - min(x))`
- Effective for algorithms that require bounded input

#### 3. Robust Scaling
- Uses the median and the interquartile range for scaling, making it robust to outliers
- Formula: `x' = (x - median)/IQR`

#### 4. MaxAbs Scaling
- Scales each feature by its maximum absolute value, resulting in values between -1 and 1
- Useful for data that is already centered at zero

### Importance of Scaling

- **Improved Convergence**: Helps gradient descent converge faster
- **Equal Feature Weight**: Ensures that features contribute equally to the distance calculations
- **Model Performance**: Can significantly affect the performance of distance-based algorithms and improve the accuracy of the model

### When to Scale

Always consider scaling when:
- Using algorithms sensitive to feature magnitudes
- Features are measured on different scales
- There are significant outliers in the data

In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([60, 100, 95, 125, 130]) 
b = np.array([1, 12, 3, 4, 5])

### Standard Scaling

In [3]:
ma, mb = np.mean(a, axis=0), np.mean(b, axis=0)
sa, sb = np.std(a, axis=0), np.std(b, axis=0)

In [4]:
scl_a = (a - ma) / sa
scl_b = (b - mb) / sb

In [7]:
print("scaled a:", scl_a)
print("scaled b:", scl_b)

scaled a: [-1.67865761 -0.07993608 -0.27977627  0.91926488  1.11910507]
scaled b: [-1.06904497  1.87082869 -0.53452248 -0.26726124  0.        ]


In [10]:
print("Mean a =", ma,", Std a:", sa)
print("Mean of scaled a:", scl_a.mean())
print("std of scaled a:", scl_a.std())

Mean a = 102.0 , Std a: 25.019992006393608
Mean of scaled a: 8.881784197001253e-17
std of scaled a: 0.9999999999999998


In [11]:
print("Mean b =", mb, ", Std b:", sb)
print("Mean of scaled b:", scl_b.mean())
print("std of scaled b:", scl_b.std())

Mean b = 5.0 , Std b: 3.7416573867739413
Mean of scaled b: -2.2204460492503132e-17
std of scaled b: 1.0


In [12]:
scl_a, scl_b

(array([-1.67865761, -0.07993608, -0.27977627,  0.91926488,  1.11910507]),
 array([-1.06904497,  1.87082869, -0.53452248, -0.26726124,  0.        ]))

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scl_std = StandardScaler()

df = pd.DataFrame({
    'a': a,
    'b': b,
})

scl_std.fit(df)

StandardScaler()

In [18]:
print("Means from StandardScaler:", scl_std.mean_)#[0], scl_std.mean_[1])
print("Means calculated manually:", ma, mb)

Means from StandardScaler: [102.   5.]
Means calculated manually: 102.0 5.0


In [19]:
scl_std.transform(df).T

array([[-1.67865761, -0.07993608, -0.27977627,  0.91926488,  1.11910507],
       [-1.06904497,  1.87082869, -0.53452248, -0.26726124,  0.        ]])

In [20]:
scl_a, scl_b

(array([-1.67865761, -0.07993608, -0.27977627,  0.91926488,  1.11910507]),
 array([-1.06904497,  1.87082869, -0.53452248, -0.26726124,  0.        ]))

### Min-Max Scaling

In [21]:
scl_a_mm = (a-a.min()) / (a.max()-a.min())
scl_b_mm = (b-b.min()) / (b.max()-b.min())

In [22]:
scl_a_mm, scl_b_mm

(array([0.        , 0.57142857, 0.5       , 0.92857143, 1.        ]),
 array([0.        , 1.        , 0.18181818, 0.27272727, 0.36363636]))

In [23]:
from sklearn.preprocessing import MinMaxScaler

In [24]:
mm_scalar = MinMaxScaler()

df = pd.DataFrame({
    'a': a,
    'b': b,
})

mm_scalar.fit(df)

MinMaxScaler()

In [25]:
mm_scalar.transform(df).T

array([[0.        , 0.57142857, 0.5       , 0.92857143, 1.        ],
       [0.        , 1.        , 0.18181818, 0.27272727, 0.36363636]])